#lang racket

(require rackunit
         cnf/private/kernel
         cnf/private/datalog
         cnf/private/schema)

;; 1. define-predicates creates named objects
(reset-store!)
(setup-schema!)
(let ()
  (define-predicates name email role)
  (check-pred string? name)
  (check-pred string? email)
  (check-not-equal? name email)
  (check-equal? (resolve-symbol "name") name)
  (check-equal? (resolve-symbol "email") email)
  (displayln "PASS 1 — define-predicates creates named objects"))

;; 2. assert! + lookup
(reset-store!)
(setup-schema!)
(let ()
  (define-predicates name email)
  (define alice (entity!))
  (assert! alice name "Alice")
  (assert! alice email "alice@co.com")
  (check-equal? (lookup alice name) "Alice")
  (check-equal? (lookup alice email) "alice@co.com")
  (displayln "PASS 2 — assert! creates values, lookup retrieves them"))

;; 3. link! + lookup (entity reference)
(reset-store!)
(setup-schema!)
(let ()
  (define-predicates name member-of)
  (define team (entity!))
  (assert! team name "Engineering")
  (define alice (entity!))
  (assert! alice name "Alice")
  (link! alice member-of team)
  (check-equal? (lookup alice member-of) team)
  (check-equal? (lookup (lookup alice member-of) name) "Engineering")
  (displayln "PASS 3 — link! creates entity reference, lookup navigates"))

;; 4. entity/claims creates entity with properties
(reset-store!)
(setup-schema!)
(let ()
  (define-predicates name email role)
  (define alice (entity/claims [name "Alice"] [email "alice@co.com"] [role "engineer"]))
  (check-equal? (lookup alice name) "Alice")
  (check-equal? (lookup alice email) "alice@co.com")
  (check-equal? (lookup alice role) "engineer")
  (displayln "PASS 4 — entity/claims creates entity with properties"))

;; 5. find-by returns matching entities
(reset-store!)
(setup-schema!)
(let ()
  (define-predicates name status)
  (define t1 (entity/claims [name "Fix bug"] [status "open"]))
  (define t2 (entity/claims [name "Add feature"] [status "closed"]))
  (define t3 (entity/claims [name "Refactor"] [status "open"]))
  (define open-tasks (find-by status "open"))
  (check-equal? (length open-tasks) 2)
  (check-not-false (member t1 open-tasks))
  (check-not-false (member t3 open-tasks))
  (check-false (member t2 open-tasks))
  (displayln "PASS 5 — find-by returns matching entities"))

;; 6. update! changes value, old superseded
(reset-store!)
(setup-schema!)
(let ()
  (define-predicates name email)
  (define alice (entity/claims [name "Alice"] [email "old@co.com"]))
  (check-equal? (lookup alice email) "old@co.com")
  (update! alice email "new@co.com")
  (check-equal? (lookup alice email) "new@co.com")
  (define all-email-claims (claims-where #:l alice #:p email))
  (check-equal? (length all-email-claims) 2)
  (displayln "PASS 6 — update! changes value via supersession"))

;; 7. retract! removes claim
(reset-store!)
(setup-schema!)
(let ()
  (define-predicates name email role)
  (define alice (entity/claims [name "Alice"] [email "alice@co.com"] [role "engineer"]))
  (check-equal? (lookup alice role) "engineer")
  (retract! alice role)
  (check-false (lookup alice role))
  (check-equal? (lookup alice name) "Alice")
  (check-equal? (lookup alice email) "alice@co.com")
  (displayln "PASS 7 — retract! removes claim, others unaffected"))

;; 8. unlink! removes entity reference
(reset-store!)
(setup-schema!)
(let ()
  (define-predicates name member-of)
  (define team-a (entity/claims [name "Team A"]))
  (define team-b (entity/claims [name "Team B"]))
  (define alice (entity!))
  (assert! alice name "Alice")
  (link! alice member-of team-a)
  (link! alice member-of team-b)
  (check-equal? (length (lookup-all alice member-of)) 2)
  (unlink! alice member-of team-a)
  (define remaining (lookup-all alice member-of))
  (check-equal? (length remaining) 1)
  (check-equal? (first remaining) team-b)
  (displayln "PASS 8 — unlink! removes specific entity link"))

;; 9. find-by works with entity references
(reset-store!)
(setup-schema!)
(let ()
  (define-predicates name assigned-to status)
  (define alice (entity/claims [name "Alice"]))
  (define bob (entity/claims [name "Bob"]))
  (define t1 (entity/claims [name "Task 1"] [status "open"]))
  (define t2 (entity/claims [name "Task 2"] [status "open"]))
  (link! t1 assigned-to alice)
  (link! t2 assigned-to bob)
  (define alice-tasks (find-by assigned-to alice))
  (check-equal? (length alice-tasks) 1)
  (check-equal? (first alice-tasks) t1)
  (displayln "PASS 9 — find-by works with entity references"))

;; 10. Multiple updates preserve full history
(reset-store!)
(setup-schema!)
(let ()
  (define-predicates name status)
  (define task (entity/claims [name "Task"] [status "todo"]))
  (update! task status "in-progress")
  (update! task status "done")
  (check-equal? (lookup task status) "done")
  (define all-status-claims (claims-where #:l task #:p status))
  (check-equal? (length all-status-claims) 3)
  (define status-vals
    (map (lambda (c) (resolve-value (list-ref c 3))) all-status-claims))
  (check-not-false (member "todo" status-vals))
  (check-not-false (member "in-progress" status-vals))
  (check-not-false (member "done" status-vals))
  (displayln "PASS 10 — multiple updates preserve full history"))

(displayln "")
(displayln "All schema tests passed.")
